version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v6-dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run: npm install @syncano/cli@canary --no-save

      - save_cache:
          paths:
            - node_modules
          key: v6-dependencies-{{ checksum "package.json" }}

      - save_cache:
          key: v6-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  test:
    name: Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v6-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run test

  deploy_staging:
    name: Deploy
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v6-repo-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys
      - run: echo '|1|BS8rJGfFqV2SXnU8vClimfxwDuc=|1QpVgk+tuVIRyREOvpIm4PQY9H4= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: echo "@syncano:registry=https://registry.npmjs.org/" >> ~/.npmrc
      - run: npm publish --tag canary --access=public

  deploy:
    name: Deploy
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v6-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: echo "@syncano:registry=https://registry.npmjs.org/" >> ~/.npmrc
      - run: npm publish --access=public

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /\d/
